version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: banking_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: banking_db
      POSTGRES_USER: bank_admin
      POSTGRES_PASSWORD: postgres455
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Database တကယ် run/no-run သိနိုင်ရန် Healthcheck ထည့်ခြင်း
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank_admin -d banking_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: